import { useDrizzle } from '../utils/drizzle'
import { ingredients } from '../db/schema'
import { count } from 'drizzle-orm'

export default defineEventHandler(async (event) => {
  const db = useDrizzle(event)

  // Check if ingredients already exist
  const result = await db.select({ count: count() }).from(ingredients)
  const existingCount = result[0]!.count

  if (existingCount > 0) {
    return {
      success: true,
      message: `Ingredients already seeded (${existingCount} items exist)`,
      skipped: true
    }
  }

  // Curated ingredient list across 9 categories
  const ingredientData: Array<{
    id: string
    name: string
    category: string
    commonNames: string[]
  }> = []

  // Helper to add ingredient with aliases
  const addIngredient = (name: string, category: string, aliases: string[] = []) => {
    ingredientData.push({
      id: crypto.randomUUID(),
      name,
      category,
      commonNames: aliases
    })
  }

  // PRODUCE (~60)
  addIngredient('onion', 'produce', ['yellow onion', 'white onion'])
  addIngredient('garlic', 'produce', ['garlic cloves'])
  addIngredient('tomato', 'produce', ['tomatoes', 'fresh tomato'])
  addIngredient('potato', 'produce', ['potatoes', 'russet potato'])
  addIngredient('carrot', 'produce', ['carrots'])
  addIngredient('bell pepper', 'produce', ['sweet pepper', 'capsicum'])
  addIngredient('broccoli', 'produce', ['broccoli florets'])
  addIngredient('spinach', 'produce', ['fresh spinach', 'baby spinach'])
  addIngredient('lettuce', 'produce', ['iceberg lettuce', 'romaine'])
  addIngredient('cucumber', 'produce', ['cucumbers'])
  addIngredient('celery', 'produce', ['celery stalks'])
  addIngredient('mushroom', 'produce', ['mushrooms', 'button mushrooms'])
  addIngredient('avocado', 'produce', ['avocados'])
  addIngredient('lemon', 'produce', ['lemons', 'fresh lemon'])
  addIngredient('lime', 'produce', ['limes', 'fresh lime'])
  addIngredient('ginger', 'produce', ['fresh ginger', 'ginger root'])
  addIngredient('cilantro', 'produce', ['coriander leaves', 'fresh cilantro'])
  addIngredient('basil', 'produce', ['fresh basil', 'sweet basil'])
  addIngredient('parsley', 'produce', ['fresh parsley'])
  addIngredient('green onion', 'produce', ['scallion', 'spring onion'])
  addIngredient('jalapeño', 'produce', ['jalapeño pepper', 'jalapeno'])
  addIngredient('zucchini', 'produce', ['courgette'])
  addIngredient('sweet potato', 'produce', ['yam', 'sweet potatoes'])
  addIngredient('corn', 'produce', ['corn kernels', 'sweet corn'])
  addIngredient('peas', 'produce', ['green peas', 'garden peas'])
  addIngredient('green beans', 'produce', ['string beans'])
  addIngredient('cabbage', 'produce', ['green cabbage'])
  addIngredient('kale', 'produce', ['curly kale'])
  addIngredient('cauliflower', 'produce', ['cauliflower florets'])
  addIngredient('eggplant', 'produce', ['aubergine'])
  addIngredient('asparagus', 'produce', ['asparagus spears'])
  addIngredient('beets', 'produce', ['beetroot'])
  addIngredient('radish', 'produce', ['radishes'])
  addIngredient('turnip', 'produce', ['turnips'])
  addIngredient('squash', 'produce', ['butternut squash'])
  addIngredient('pumpkin', 'produce', ['pumpkin puree'])
  addIngredient('mango', 'produce', ['mangoes', 'fresh mango'])
  addIngredient('banana', 'produce', ['bananas'])
  addIngredient('apple', 'produce', ['apples'])
  addIngredient('orange', 'produce', ['oranges'])
  addIngredient('strawberry', 'produce', ['strawberries', 'fresh strawberries'])
  addIngredient('blueberry', 'produce', ['blueberries', 'fresh blueberries'])
  addIngredient('raspberry', 'produce', ['raspberries'])
  addIngredient('pineapple', 'produce', ['fresh pineapple'])
  addIngredient('coconut', 'produce', ['shredded coconut', 'coconut flakes'])
  addIngredient('peach', 'produce', ['peaches', 'fresh peach'])
  addIngredient('pear', 'produce', ['pears'])
  addIngredient('grape', 'produce', ['grapes'])
  addIngredient('watermelon', 'produce', ['fresh watermelon'])
  addIngredient('cherry', 'produce', ['cherries'])
  addIngredient('fig', 'produce', ['figs', 'fresh figs'])
  addIngredient('date', 'produce', ['dates', 'medjool dates'])
  addIngredient('pomegranate', 'produce', ['pomegranate seeds'])
  addIngredient('papaya', 'produce', ['papayas'])
  addIngredient('kiwi', 'produce', ['kiwi fruit'])
  addIngredient('plum', 'produce', ['plums'])
  addIngredient('cranberry', 'produce', ['cranberries'])
  addIngredient('blackberry', 'produce', ['blackberries'])
  addIngredient('cantaloupe', 'produce', ['melon'])
  addIngredient('honeydew', 'produce', ['honeydew melon'])

  // PROTEIN (~40)
  addIngredient('chicken breast', 'protein', ['chicken breasts', 'boneless chicken'])
  addIngredient('chicken thigh', 'protein', ['chicken thighs'])
  addIngredient('ground beef', 'protein', ['minced beef', 'beef mince'])
  addIngredient('steak', 'protein', ['beef steak', 'sirloin'])
  addIngredient('pork chop', 'protein', ['pork chops'])
  addIngredient('pork tenderloin', 'protein', ['pork fillet'])
  addIngredient('bacon', 'protein', ['bacon strips'])
  addIngredient('sausage', 'protein', ['sausages', 'Italian sausage'])
  addIngredient('ground turkey', 'protein', ['turkey mince'])
  addIngredient('lamb', 'protein', ['lamb chops', 'lamb shoulder'])
  addIngredient('salmon', 'protein', ['salmon fillet', 'fresh salmon'])
  addIngredient('tuna', 'protein', ['tuna steak', 'fresh tuna'])
  addIngredient('shrimp', 'protein', ['prawns', 'shrimps'])
  addIngredient('cod', 'protein', ['cod fillet'])
  addIngredient('tilapia', 'protein', ['tilapia fillet'])
  addIngredient('crab', 'protein', ['crab meat', 'lump crab'])
  addIngredient('lobster', 'protein', ['lobster tail'])
  addIngredient('scallops', 'protein', ['sea scallops'])
  addIngredient('mussels', 'protein', ['fresh mussels'])
  addIngredient('clams', 'protein', ['fresh clams'])
  addIngredient('tofu', 'protein', ['firm tofu', 'silken tofu'])
  addIngredient('tempeh', 'protein', ['soy tempeh'])
  addIngredient('seitan', 'protein', ['wheat gluten'])
  addIngredient('eggs', 'protein', ['chicken eggs', 'large eggs'])
  addIngredient('duck', 'protein', ['duck breast'])
  addIngredient('veal', 'protein', ['veal cutlet'])
  addIngredient('bison', 'protein', ['buffalo meat'])
  addIngredient('anchovies', 'protein', ['anchovy fillets'])
  addIngredient('sardines', 'protein', ['canned sardines'])
  addIngredient('trout', 'protein', ['rainbow trout'])
  addIngredient('catfish', 'protein', ['catfish fillet'])
  addIngredient('swordfish', 'protein', ['swordfish steak'])
  addIngredient('halibut', 'protein', ['halibut fillet'])
  addIngredient('mahi-mahi', 'protein', ['dorado'])
  addIngredient('octopus', 'protein', ['fresh octopus'])
  addIngredient('squid', 'protein', ['calamari'])
  addIngredient('venison', 'protein', ['deer meat'])
  addIngredient('rabbit', 'protein', ['rabbit meat'])
  addIngredient('turkey breast', 'protein', ['turkey cutlet'])
  addIngredient('ham', 'protein', ['deli ham', 'smoked ham'])

  // DAIRY (~25)
  addIngredient('butter', 'dairy', ['unsalted butter', 'salted butter'])
  addIngredient('milk', 'dairy', ['whole milk', 'cow milk'])
  addIngredient('heavy cream', 'dairy', ['whipping cream', 'double cream'])
  addIngredient('sour cream', 'dairy', ['soured cream'])
  addIngredient('cream cheese', 'dairy', ['soft cheese'])
  addIngredient('cheddar cheese', 'dairy', ['cheddar'])
  addIngredient('mozzarella', 'dairy', ['fresh mozzarella', 'mozzarella cheese'])
  addIngredient('parmesan', 'dairy', ['parmigiano-reggiano', 'parmesan cheese'])
  addIngredient('feta', 'dairy', ['feta cheese'])
  addIngredient('goat cheese', 'dairy', ['chèvre'])
  addIngredient('ricotta', 'dairy', ['ricotta cheese'])
  addIngredient('yogurt', 'dairy', ['plain yogurt'])
  addIngredient('greek yogurt', 'dairy', ['Greek-style yogurt'])
  addIngredient('brie', 'dairy', ['brie cheese'])
  addIngredient('gruyere', 'dairy', ['gruyère cheese'])
  addIngredient('swiss cheese', 'dairy', ['Emmental'])
  addIngredient('blue cheese', 'dairy', ['Roquefort', 'Gorgonzola'])
  addIngredient('mascarpone', 'dairy', ['mascarpone cheese'])
  addIngredient('condensed milk', 'dairy', ['sweetened condensed milk'])
  addIngredient('evaporated milk', 'dairy', ['unsweetened condensed milk'])
  addIngredient('buttermilk', 'dairy', ['cultured buttermilk'])
  addIngredient('half-and-half', 'dairy', ['half and half cream'])
  addIngredient('whipped cream', 'dairy', ['whipping cream'])
  addIngredient('ghee', 'dairy', ['clarified butter'])
  addIngredient('cottage cheese', 'dairy', ['curds'])

  // GRAINS (~30)
  addIngredient('all-purpose flour', 'grains', ['plain flour', 'AP flour'])
  addIngredient('bread flour', 'grains', ['strong flour'])
  addIngredient('rice', 'grains', ['white rice', 'long grain rice'])
  addIngredient('pasta', 'grains', ['dried pasta', 'spaghetti'])
  addIngredient('bread', 'grains', ['white bread', 'sliced bread'])
  addIngredient('tortilla', 'grains', ['flour tortilla'])
  addIngredient('couscous', 'grains', ['Moroccan couscous'])
  addIngredient('quinoa', 'grains', ['white quinoa'])
  addIngredient('oats', 'grains', ['rolled oats', 'oatmeal'])
  addIngredient('cornmeal', 'grains', ['polenta'])
  addIngredient('panko breadcrumbs', 'grains', ['Japanese breadcrumbs', 'panko'])
  addIngredient('pita', 'grains', ['pita bread'])
  addIngredient('naan', 'grains', ['naan bread'])
  addIngredient('ramen noodles', 'grains', ['ramen'])
  addIngredient('udon noodles', 'grains', ['udon'])
  addIngredient('soba noodles', 'grains', ['buckwheat noodles'])
  addIngredient('rice noodles', 'grains', ['rice stick noodles'])
  addIngredient('egg noodles', 'grains', ['fresh egg noodles'])
  addIngredient('barley', 'grains', ['pearl barley'])
  addIngredient('farro', 'grains', ['emmer wheat'])
  addIngredient('bulgur', 'grains', ['bulgur wheat'])
  addIngredient('polenta', 'grains', ['cornmeal'])
  addIngredient('grits', 'grains', ['hominy grits'])
  addIngredient('semolina', 'grains', ['semolina flour'])
  addIngredient('tapioca', 'grains', ['tapioca starch'])
  addIngredient('corn tortilla', 'grains', ['corn tortillas'])
  addIngredient('flour tortilla', 'grains', ['wheat tortilla'])
  addIngredient('pizza dough', 'grains', ['pizza base'])
  addIngredient('puff pastry', 'grains', ['puff pastry sheets'])
  addIngredient('phyllo dough', 'grains', ['filo pastry'])

  // SPICES (~50)
  addIngredient('salt', 'spices', ['table salt', 'sea salt'])
  addIngredient('black pepper', 'spices', ['ground black pepper'])
  addIngredient('cumin', 'spices', ['ground cumin', 'cumin powder'])
  addIngredient('paprika', 'spices', ['sweet paprika'])
  addIngredient('chili powder', 'spices', ['chile powder'])
  addIngredient('cayenne', 'spices', ['cayenne pepper'])
  addIngredient('turmeric', 'spices', ['ground turmeric'])
  addIngredient('cinnamon', 'spices', ['ground cinnamon'])
  addIngredient('nutmeg', 'spices', ['ground nutmeg'])
  addIngredient('oregano', 'spices', ['dried oregano'])
  addIngredient('thyme', 'spices', ['dried thyme'])
  addIngredient('rosemary', 'spices', ['dried rosemary'])
  addIngredient('bay leaves', 'spices', ['bay leaf'])
  addIngredient('coriander', 'spices', ['ground coriander'])
  addIngredient('cardamom', 'spices', ['ground cardamom'])
  addIngredient('cloves', 'spices', ['whole cloves'])
  addIngredient('allspice', 'spices', ['ground allspice'])
  addIngredient('star anise', 'spices', ['whole star anise'])
  addIngredient('fennel seeds', 'spices', ['fennel'])
  addIngredient('mustard seeds', 'spices', ['yellow mustard seeds'])
  addIngredient('red pepper flakes', 'spices', ['crushed red pepper', 'chili flakes'])
  addIngredient('smoked paprika', 'spices', ['pimentón'])
  addIngredient('garlic powder', 'spices', ['dried garlic'])
  addIngredient('onion powder', 'spices', ['dried onion'])
  addIngredient('italian seasoning', 'spices', ['Italian herbs'])
  addIngredient('curry powder', 'spices', ['curry spice'])
  addIngredient('garam masala', 'spices', ['Indian spice blend'])
  addIngredient('five-spice', 'spices', ['Chinese five-spice'])
  addIngredient('za\'atar', 'spices', ['zaatar'])
  addIngredient('sumac', 'spices', ['ground sumac'])
  addIngredient('saffron', 'spices', ['saffron threads'])
  addIngredient('white pepper', 'spices', ['ground white pepper'])
  addIngredient('dill', 'spices', ['dried dill', 'dill weed'])
  addIngredient('tarragon', 'spices', ['dried tarragon'])
  addIngredient('sage', 'spices', ['dried sage'])
  addIngredient('marjoram', 'spices', ['dried marjoram'])
  addIngredient('celery salt', 'spices', ['celery seasoning'])
  addIngredient('Old Bay', 'spices', ['Old Bay seasoning'])
  addIngredient('chili flakes', 'spices', ['red chili flakes'])
  addIngredient('szechuan peppercorn', 'spices', ['Sichuan pepper'])
  addIngredient('lemongrass', 'spices', ['lemongrass stalks'])
  addIngredient('galangal', 'spices', ['Thai ginger'])
  addIngredient('dried basil', 'spices', ['basil leaves'])
  addIngredient('dried parsley', 'spices', ['parsley flakes'])
  addIngredient('vanilla extract', 'spices', ['vanilla essence'])
  addIngredient('almond extract', 'spices', ['almond essence'])
  addIngredient('mint', 'spices', ['dried mint'])
  addIngredient('lavender', 'spices', ['dried lavender'])
  addIngredient('juniper berries', 'spices', ['juniper'])
  addIngredient('caraway seeds', 'spices', ['caraway'])
  addIngredient('berbere', 'spices', ['berbere spice', 'Ethiopian spice blend'])
  addIngredient('harissa', 'spices', ['harissa paste', 'harissa powder'])
  addIngredient('ras el hanout', 'spices', ['Moroccan spice blend'])
  addIngredient('gochugaru', 'spices', ['Korean chili flakes', 'Korean red pepper flakes'])
  addIngredient('gochujang', 'spices', ['Korean chili paste', 'Korean red pepper paste'])
  addIngredient('togarashi', 'spices', ['shichimi togarashi', 'seven spice'])
  addIngredient('furikake', 'spices', ['rice seasoning'])
  addIngredient('tajin', 'spices', ['Tajín seasoning', 'chili lime seasoning'])
  addIngredient('adobo seasoning', 'spices', ['adobo'])
  addIngredient('chipotle', 'spices', ['chipotle powder', 'chipotle pepper'])
  addIngredient('ancho chili', 'spices', ['ancho powder', 'dried ancho'])
  addIngredient('curry leaves', 'spices', ['fresh curry leaves'])
  addIngredient('fenugreek', 'spices', ['fenugreek seeds', 'methi'])
  addIngredient('asafoetida', 'spices', ['hing'])
  addIngredient('annatto', 'spices', ['achiote', 'annatto seeds'])
  addIngredient('nigella seeds', 'spices', ['black cumin', 'kalonji'])
  addIngredient('herbes de Provence', 'spices', ['Provence herbs'])
  addIngredient('everything bagel seasoning', 'spices', ['everything seasoning'])
  addIngredient('ranch seasoning', 'spices', ['ranch powder'])
  addIngredient('taco seasoning', 'spices', ['taco spice mix'])
  addIngredient('jerk seasoning', 'spices', ['Jamaican jerk spice'])
  addIngredient('dukkah', 'spices', ['Egyptian nut spice blend'])

  // CONDIMENTS (~35)
  addIngredient('soy sauce', 'condiments', ['light soy sauce'])
  addIngredient('olive oil', 'condiments', ['extra virgin olive oil', 'EVOO'])
  addIngredient('vegetable oil', 'condiments', ['canola oil', 'cooking oil'])
  addIngredient('sesame oil', 'condiments', ['toasted sesame oil'])
  addIngredient('vinegar', 'condiments', ['white vinegar'])
  addIngredient('balsamic vinegar', 'condiments', ['balsamic'])
  addIngredient('rice vinegar', 'condiments', ['rice wine vinegar'])
  addIngredient('apple cider vinegar', 'condiments', ['ACV', 'cider vinegar'])
  addIngredient('honey', 'condiments', ['raw honey'])
  addIngredient('maple syrup', 'condiments', ['pure maple syrup'])
  addIngredient('ketchup', 'condiments', ['tomato ketchup'])
  addIngredient('mustard', 'condiments', ['yellow mustard'])
  addIngredient('dijon mustard', 'condiments', ['Dijon'])
  addIngredient('mayonnaise', 'condiments', ['mayo'])
  addIngredient('hot sauce', 'condiments', ['Tabasco', 'Louisiana hot sauce'])
  addIngredient('sriracha', 'condiments', ['sriracha sauce'])
  addIngredient('worcestershire sauce', 'condiments', ['Worcestershire'])
  addIngredient('fish sauce', 'condiments', ['nam pla'])
  addIngredient('oyster sauce', 'condiments', ['oyster flavored sauce'])
  addIngredient('hoisin sauce', 'condiments', ['hoisin'])
  addIngredient('tahini', 'condiments', ['sesame paste'])
  addIngredient('miso paste', 'condiments', ['miso', 'white miso'])
  addIngredient('tomato paste', 'condiments', ['tomato concentrate'])
  addIngredient('tomato sauce', 'condiments', ['tomato puree'])
  addIngredient('coconut milk', 'condiments', ['canned coconut milk'])
  addIngredient('coconut cream', 'condiments', ['thick coconut milk'])
  addIngredient('peanut butter', 'condiments', ['smooth peanut butter'])
  addIngredient('almond butter', 'condiments', ['almond spread'])
  addIngredient('jam', 'condiments', ['jelly', 'preserves'])
  addIngredient('salsa', 'condiments', ['tomato salsa'])
  addIngredient('barbecue sauce', 'condiments', ['BBQ sauce'])
  addIngredient('teriyaki sauce', 'condiments', ['teriyaki'])
  addIngredient('chili garlic sauce', 'condiments', ['chili sauce'])
  addIngredient('sambal oelek', 'condiments', ['sambal'])
  addIngredient('harissa', 'condiments', ['harissa paste'])

  // BAKING (~25)
  addIngredient('sugar', 'baking', ['white sugar', 'granulated sugar'])
  addIngredient('brown sugar', 'baking', ['light brown sugar'])
  addIngredient('powdered sugar', 'baking', ['icing sugar', 'confectioners sugar'])
  addIngredient('baking soda', 'baking', ['bicarbonate of soda'])
  addIngredient('baking powder', 'baking', ['baking powder'])
  addIngredient('yeast', 'baking', ['active dry yeast'])
  addIngredient('cocoa powder', 'baking', ['unsweetened cocoa'])
  addIngredient('chocolate chips', 'baking', ['semi-sweet chocolate chips'])
  addIngredient('vanilla', 'baking', ['vanilla bean'])
  addIngredient('cornstarch', 'baking', ['corn flour', 'cornflour'])
  addIngredient('gelatin', 'baking', ['unflavored gelatin'])
  addIngredient('molasses', 'baking', ['blackstrap molasses'])
  addIngredient('corn syrup', 'baking', ['light corn syrup'])
  addIngredient('agave', 'baking', ['agave nectar', 'agave syrup'])
  addIngredient('coconut sugar', 'baking', ['palm sugar'])
  addIngredient('food coloring', 'baking', ['food dye'])
  addIngredient('cream of tartar', 'baking', ['tartaric acid'])
  addIngredient('meringue powder', 'baking', ['powdered egg whites'])
  addIngredient('cocoa butter', 'baking', ['cacao butter'])
  addIngredient('white chocolate', 'baking', ['white chocolate chips'])
  addIngredient('dark chocolate', 'baking', ['dark chocolate chips'])
  addIngredient('milk chocolate', 'baking', ['milk chocolate chips'])
  addIngredient('sprinkles', 'baking', ['jimmies'])
  addIngredient('coconut flakes', 'baking', ['desiccated coconut'])
  addIngredient('almond flour', 'baking', ['almond meal'])

  // CANNED (~20)
  addIngredient('canned tomatoes', 'canned', ['diced tomatoes', 'crushed tomatoes'])
  addIngredient('chickpeas', 'canned', ['garbanzo beans', 'canned chickpeas'])
  addIngredient('black beans', 'canned', ['canned black beans'])
  addIngredient('kidney beans', 'canned', ['red kidney beans'])
  addIngredient('white beans', 'canned', ['cannellini beans'])
  addIngredient('lentils', 'canned', ['canned lentils'])
  addIngredient('green chiles', 'canned', ['canned green chilies'])
  addIngredient('olives', 'canned', ['black olives', 'green olives'])
  addIngredient('artichoke hearts', 'canned', ['canned artichokes'])
  addIngredient('hearts of palm', 'canned', ['palmito'])
  addIngredient('water chestnuts', 'canned', ['canned water chestnuts'])
  addIngredient('bamboo shoots', 'canned', ['canned bamboo'])
  addIngredient('capers', 'canned', ['brined capers'])
  addIngredient('sun-dried tomatoes', 'canned', ['sundried tomatoes'])
  addIngredient('roasted red peppers', 'canned', ['jarred roasted peppers'])
  addIngredient('pumpkin puree', 'canned', ['canned pumpkin'])
  addIngredient('cranberry sauce', 'canned', ['jellied cranberry'])
  addIngredient('tuna', 'canned', ['canned tuna'])
  addIngredient('salmon', 'canned', ['canned salmon'])
  addIngredient('corn', 'canned', ['canned corn'])

  // NUTS_SEEDS (~15)
  addIngredient('almonds', 'nuts_seeds', ['whole almonds', 'sliced almonds'])
  addIngredient('walnuts', 'nuts_seeds', ['walnut halves'])
  addIngredient('pecans', 'nuts_seeds', ['pecan halves'])
  addIngredient('cashews', 'nuts_seeds', ['whole cashews'])
  addIngredient('peanuts', 'nuts_seeds', ['roasted peanuts'])
  addIngredient('pistachios', 'nuts_seeds', ['shelled pistachios'])
  addIngredient('pine nuts', 'nuts_seeds', ['pignoli'])
  addIngredient('macadamia nuts', 'nuts_seeds', ['macadamias'])
  addIngredient('hazelnuts', 'nuts_seeds', ['filberts'])
  addIngredient('sunflower seeds', 'nuts_seeds', ['sunflower kernels'])
  addIngredient('pumpkin seeds', 'nuts_seeds', ['pepitas'])
  addIngredient('sesame seeds', 'nuts_seeds', ['white sesame seeds'])
  addIngredient('chia seeds', 'nuts_seeds', ['chia'])
  addIngredient('flax seeds', 'nuts_seeds', ['flaxseed', 'linseed'])
  addIngredient('hemp seeds', 'nuts_seeds', ['hemp hearts'])

  // Insert one by one (batch inserts fail in local D1)
  let insertedCount = 0

  for (const item of ingredientData) {
    await db.insert(ingredients).values({
      id: item.id,
      name: item.name,
      category: item.category,
      commonNames: JSON.stringify(item.commonNames),
      createdAt: new Date()
    })
    insertedCount++
  }

  return {
    success: true,
    message: `Seeded ${insertedCount} ingredients across 9 categories`,
    stats: {
      total: insertedCount,
      byCategory: {
        produce: ingredientData.filter(i => i.category === 'produce').length,
        protein: ingredientData.filter(i => i.category === 'protein').length,
        dairy: ingredientData.filter(i => i.category === 'dairy').length,
        grains: ingredientData.filter(i => i.category === 'grains').length,
        spices: ingredientData.filter(i => i.category === 'spices').length,
        condiments: ingredientData.filter(i => i.category === 'condiments').length,
        baking: ingredientData.filter(i => i.category === 'baking').length,
        canned: ingredientData.filter(i => i.category === 'canned').length,
        nuts_seeds: ingredientData.filter(i => i.category === 'nuts_seeds').length
      }
    }
  }
})
