/**
 * Per-ingredient emoji lookup with category fallback.
 * Covers all 305 seeded ingredients across 9 categories.
 */

// --- Category fallback map ---
const categoryEmojiMap: Record<string, string> = {
  produce: '🥬',
  protein: '🍖',
  dairy: '🧀',
  grains: '🌾',
  spices: '🧂',
  condiments: '🫙',
  baking: '🧁',
  canned: '🥫',
  nuts_seeds: '🥜',
}

// --- Per-ingredient emoji map (lowercase keys) ---
const ingredientEmojiMap: Record<string, string> = {
  // PRODUCE - vegetables
  onion: '🧅',
  'yellow onion': '🧅',
  'white onion': '🧅',
  garlic: '🧄',
  tomato: '🍅',
  tomatoes: '🍅',
  potato: '🥔',
  potatoes: '🥔',
  'sweet potato': '🍠',
  carrot: '🥕',
  carrots: '🥕',
  'bell pepper': '🫑',
  broccoli: '🥦',
  spinach: '🥬',
  lettuce: '🥬',
  cucumber: '🥒',
  cucumbers: '🥒',
  celery: '🥦',
  mushroom: '🍄',
  mushrooms: '🍄',
  avocado: '🥑',
  avocados: '🥑',
  lemon: '🍋',
  lemons: '🍋',
  lime: '🍋',
  limes: '🍋',
  ginger: '🫚',
  cilantro: '🌿',
  basil: '🌿',
  parsley: '🌿',
  'green onion': '🧅',
  scallion: '🧅',
  'spring onion': '🧅',
  jalapeño: '🌶️',
  jalapeno: '🌶️',
  zucchini: '🥒',
  courgette: '🥒',
  corn: '🌽',
  peas: '🫛',
  'green beans': '🫛',
  cabbage: '🥬',
  kale: '🥬',
  cauliflower: '🥦',
  eggplant: '🍆',
  asparagus: '🌿',
  beets: '🫐',
  radish: '🔴',
  turnip: '🥔',
  squash: '🎃',
  pumpkin: '🎃',
  // PRODUCE - fruits
  mango: '🥭',
  mangoes: '🥭',
  banana: '🍌',
  bananas: '🍌',
  apple: '🍎',
  apples: '🍎',
  orange: '🍊',
  oranges: '🍊',
  strawberry: '🍓',
  strawberries: '🍓',
  blueberry: '🫐',
  blueberries: '🫐',
  raspberry: '🍓',
  raspberries: '🍓',
  pineapple: '🍍',
  coconut: '🥥',
  peach: '🍑',
  peaches: '🍑',
  pear: '🍐',
  pears: '🍐',
  grape: '🍇',
  grapes: '🍇',
  watermelon: '🍉',
  cherry: '🍒',
  cherries: '🍒',
  fig: '🍑',
  figs: '🍑',
  date: '🟤',
  dates: '🟤',
  pomegranate: '🍎',
  papaya: '🥭',
  kiwi: '🥝',
  plum: '🍇',
  plums: '🍇',
  cranberry: '🍒',
  cranberries: '🍒',
  blackberry: '🫐',
  blackberries: '🫐',
  cantaloupe: '🍈',
  honeydew: '🍈',
  // PROTEIN - meat
  'chicken breast': '🍗',
  'chicken thigh': '🍗',
  chicken: '🍗',
  'ground beef': '🥩',
  steak: '🥩',
  beef: '🥩',
  'pork chop': '🥩',
  'pork tenderloin': '🥩',
  pork: '🥩',
  bacon: '🥓',
  sausage: '🌭',
  sausages: '🌭',
  'ground turkey': '🦃',
  lamb: '🥩',
  // PROTEIN - seafood
  salmon: '🐟',
  tuna: '🐟',
  shrimp: '🦐',
  prawns: '🦐',
  cod: '🐟',
  tilapia: '🐟',
  crab: '🦀',
  lobster: '🦞',
  scallops: '🐚',
  mussels: '🦪',
  clams: '🦪',
  trout: '🐟',
  catfish: '🐟',
  swordfish: '🐟',
  halibut: '🐟',
  'mahi-mahi': '🐟',
  octopus: '🐙',
  squid: '🦑',
  anchovies: '🐟',
  sardines: '🐟',
  // PROTEIN - other
  tofu: '🧈',
  tempeh: '🧈',
  seitan: '🧈',
  eggs: '🥚',
  egg: '🥚',
  duck: '🦆',
  veal: '🥩',
  bison: '🥩',
  venison: '🥩',
  rabbit: '🐇',
  'turkey breast': '🦃',
  turkey: '🦃',
  ham: '🥩',
  // DAIRY
  butter: '🧈',
  milk: '🥛',
  'heavy cream': '🥛',
  'sour cream': '🥛',
  'cream cheese': '🧀',
  'cheddar cheese': '🧀',
  cheddar: '🧀',
  mozzarella: '🧀',
  parmesan: '🧀',
  feta: '🧀',
  'goat cheese': '🧀',
  ricotta: '🧀',
  yogurt: '🫙',
  'greek yogurt': '🫙',
  brie: '🧀',
  gruyere: '🧀',
  'swiss cheese': '🧀',
  'blue cheese': '🧀',
  mascarpone: '🧀',
  'condensed milk': '🥛',
  'evaporated milk': '🥛',
  buttermilk: '🥛',
  'half-and-half': '🥛',
  'whipped cream': '🍦',
  ghee: '🧈',
  'cottage cheese': '🧀',
  cheese: '🧀',
  // GRAINS
  'all-purpose flour': '🌾',
  'bread flour': '🌾',
  flour: '🌾',
  rice: '🍚',
  pasta: '🍝',
  spaghetti: '🍝',
  bread: '🍞',
  tortilla: '🫓',
  couscous: '🌾',
  quinoa: '🌾',
  oats: '🥣',
  oatmeal: '🥣',
  cornmeal: '🌽',
  polenta: '🌽',
  'panko breadcrumbs': '🍞',
  panko: '🍞',
  pita: '🫓',
  naan: '🫓',
  'ramen noodles': '🍜',
  ramen: '🍜',
  'udon noodles': '🍜',
  udon: '🍜',
  'soba noodles': '🍜',
  'rice noodles': '🍜',
  'egg noodles': '🍜',
  barley: '🌾',
  farro: '🌾',
  bulgur: '🌾',
  grits: '🌾',
  semolina: '🌾',
  tapioca: '🌾',
  'corn tortilla': '🫓',
  'flour tortilla': '🫓',
  'pizza dough': '🍕',
  'puff pastry': '🥐',
  'phyllo dough': '🥐',
  // SPICES
  salt: '🧂',
  'black pepper': '🧂',
  pepper: '🧂',
  cumin: '🧂',
  paprika: '🌶️',
  'chili powder': '🌶️',
  cayenne: '🌶️',
  turmeric: '🟡',
  cinnamon: '🧂',
  nutmeg: '🧂',
  oregano: '🌿',
  thyme: '🌿',
  rosemary: '🌿',
  'bay leaves': '🍃',
  'bay leaf': '🍃',
  coriander: '🌿',
  cardamom: '🧂',
  cloves: '🧂',
  allspice: '🧂',
  'star anise': '⭐',
  'fennel seeds': '🌿',
  'mustard seeds': '🟡',
  'red pepper flakes': '🌶️',
  'smoked paprika': '🌶️',
  'garlic powder': '🧄',
  'onion powder': '🧅',
  'italian seasoning': '🌿',
  'curry powder': '🟡',
  'garam masala': '🧂',
  'five-spice': '🧂',
  "za'atar": '🌿',
  zaatar: '🌿',
  sumac: '🧂',
  saffron: '🟡',
  'white pepper': '🧂',
  dill: '🌿',
  tarragon: '🌿',
  sage: '🌿',
  marjoram: '🌿',
  'celery salt': '🧂',
  'old bay': '🧂',
  'chili flakes': '🌶️',
  'szechuan peppercorn': '🧂',
  lemongrass: '🌿',
  galangal: '🫚',
  'dried basil': '🌿',
  'dried parsley': '🌿',
  'vanilla extract': '🍶',
  vanilla: '🍶',
  'almond extract': '🍶',
  mint: '🌿',
  lavender: '💜',
  'juniper berries': '🫐',
  'caraway seeds': '🧂',
  berbere: '🧂',
  harissa: '🌶️',
  'ras el hanout': '🧂',
  gochugaru: '🌶️',
  gochujang: '🌶️',
  togarashi: '🌶️',
  furikake: '🧂',
  tajin: '🌶️',
  'adobo seasoning': '🧂',
  adobo: '🧂',
  chipotle: '🌶️',
  'ancho chili': '🌶️',
  'curry leaves': '🍃',
  fenugreek: '🧂',
  asafoetida: '🧂',
  annatto: '🟡',
  'nigella seeds': '🧂',
  'herbes de provence': '🌿',
  'everything bagel seasoning': '🧂',
  'ranch seasoning': '🧂',
  'taco seasoning': '🧂',
  'jerk seasoning': '🌶️',
  dukkah: '🧂',
  // CONDIMENTS
  'soy sauce': '🥢',
  'olive oil': '🫒',
  oil: '🫙',
  'vegetable oil': '🫙',
  'sesame oil': '🫙',
  vinegar: '🫙',
  'balsamic vinegar': '🫙',
  'rice vinegar': '🫙',
  'apple cider vinegar': '🍎',
  honey: '🍯',
  'maple syrup': '🍁',
  ketchup: '🍅',
  mustard: '🌭',
  'dijon mustard': '🌭',
  mayonnaise: '🫙',
  mayo: '🫙',
  'hot sauce': '🌶️',
  sriracha: '🌶️',
  'worcestershire sauce': '🫙',
  'fish sauce': '🐟',
  'oyster sauce': '🦪',
  'hoisin sauce': '🫙',
  tahini: '🫙',
  'miso paste': '🫙',
  miso: '🫙',
  'tomato paste': '🍅',
  'tomato sauce': '🍅',
  'coconut milk': '🥥',
  'coconut cream': '🥥',
  'peanut butter': '🥜',
  'almond butter': '🥜',
  jam: '🍓',
  jelly: '🍓',
  salsa: '🍅',
  'barbecue sauce': '🔥',
  'teriyaki sauce': '🍶',
  'chili garlic sauce': '🌶️',
  'sambal oelek': '🌶️',
  sambal: '🌶️',
  // BAKING
  sugar: '🍬',
  'brown sugar': '🍬',
  'powdered sugar': '🍬',
  'baking soda': '🧁',
  'baking powder': '🧁',
  yeast: '🧁',
  'cocoa powder': '🍫',
  'chocolate chips': '🍫',
  'dark chocolate': '🍫',
  'white chocolate': '🍫',
  'milk chocolate': '🍫',
  chocolate: '🍫',
  cornstarch: '🌽',
  gelatin: '🧁',
  molasses: '🍯',
  'corn syrup': '🫙',
  agave: '🌵',
  'coconut sugar': '🥥',
  'food coloring': '🎨',
  'cream of tartar': '🧁',
  'meringue powder': '🧁',
  'cocoa butter': '🍫',
  sprinkles: '🎉',
  'coconut flakes': '🥥',
  'almond flour': '🌰',
  cookie: '🍪',
  cookies: '🍪',
  // CANNED
  'canned tomatoes': '🥫',
  chickpeas: '🫘',
  'garbanzo beans': '🫘',
  'black beans': '🫘',
  'kidney beans': '🫘',
  'white beans': '🫘',
  lentils: '🫘',
  beans: '🫘',
  'green chiles': '🌶️',
  olives: '🫒',
  'artichoke hearts': '🌿',
  'hearts of palm': '🌿',
  'water chestnuts': '🌰',
  'bamboo shoots': '🎋',
  capers: '🫒',
  'sun-dried tomatoes': '🍅',
  'roasted red peppers': '🫑',
  'pumpkin puree': '🎃',
  'cranberry sauce': '🍒',
  // NUTS_SEEDS
  almonds: '🌰',
  walnuts: '🌰',
  pecans: '🌰',
  cashews: '🌰',
  peanuts: '🥜',
  pistachios: '🌰',
  'pine nuts': '🌰',
  'macadamia nuts': '🌰',
  hazelnuts: '🌰',
  'sunflower seeds': '🌻',
  'pumpkin seeds': '🎃',
  'sesame seeds': '🌾',
  'chia seeds': '🌱',
  'flax seeds': '🌱',
  'hemp seeds': '🌱',
  chestnuts: '🌰',
  nuts: '🌰',
}

/**
 * Returns the best emoji for a given ingredient name and optional category.
 *
 * Lookup order:
 * 1. Exact match on full name (lowercase)
 * 2. Exact match on first word of name
 * 3. Category fallback (if category provided)
 * 4. Generic food fallback
 */
export function getIngredientEmoji(name: string, category?: string): string {
  const normalized = name.toLowerCase().trim()

  // 1. Exact match
  if (ingredientEmojiMap[normalized]) {
    return ingredientEmojiMap[normalized]!
  }

  // 2. First-word match (e.g., "chicken breast" → "chicken")
  const firstWord = normalized.split(' ')[0]
  if (firstWord && firstWord !== normalized && ingredientEmojiMap[firstWord]) {
    return ingredientEmojiMap[firstWord]!
  }

  // 3. Category fallback
  if (category) {
    const catEmoji = categoryEmojiMap[category.toLowerCase()]
    if (catEmoji) return catEmoji
  }

  // 4. Final fallback
  return '🍽️'
}

/**
 * Returns the category emoji for cases where only category is available.
 */
export function getCategoryEmoji(category: string): string {
  return categoryEmojiMap[category.toLowerCase()] ?? '🍽️'
}
